POST http://localhost:4700/model
Content-Type: application/json

{
    "location": "Hyderabad",
    "date": "Wed Feb 12 2025 22:50:13 GMT+0530 (India Standard Time)",
    "gender": "male"
}

###

POST http://localhost:4700/model/try-on
Content-Type: application/json

{
    "model_image":"D:\\Outfit Assistant\\server\\APIs\\assets\\portpic.jpg",
    "cloth_image":"D:\\Outfit Assistant\\server\\APIs\\assets\\image.png"
}